<x-app-layout>
<div class="page">
    <header class="page-header" data-reveal><div><h1>Laporan keuangan</h1><p class="muted mt-2">Lihat pola kecil di balik rencana besarmu.</p></div><x-action-bar><x-button variant="secondary" :href="route('reports.export', ['start_date' => $startDate, 'end_date' => $endDate])" icon="download-simple">Unduh PDF</x-button></x-action-bar></header>
    <form action="{{ route('reports.index') }}" method="GET" class="panel grid md:grid-cols-3 gap-4 items-end"><x-field name="start_date" label="Mulai tanggal" type="date" :value="$startDate" required /><x-field name="end_date" label="Sampai tanggal" type="date" :value="$endDate" required /><x-button type="submit" icon="funnel">Terapkan periode</x-button></form>
    <p class="muted">Periode: {{ \Carbon\Carbon::parse($startDate)->locale('id')->translatedFormat('j M Y') }} – {{ \Carbon\Carbon::parse($endDate)->locale('id')->translatedFormat('j M Y') }}</p>
    <section class="pocket summary-panel stack" data-palette="yellow" data-reveal><span class="pocket-tab" aria-hidden="true"></span><h2>Arus kas bersih</h2><x-money :value="$cashflow" class="balance block" :count="true" /><p class="muted">{{ $cashflow >= 0 ? 'Pemasukan setidaknya menutup pengeluaran pada periode ini.' : 'Pengeluaran melebihi pemasukan pada periode ini.' }}</p></section>
    <div class="grid sm:grid-cols-2 gap-6">@foreach([['Pemasukan', 'success', $totalIncome], ['Pengeluaran', 'danger', $totalExpense]] as [$label, $tone, $value])<section class="panel stack" data-reveal><x-badge :tone="$tone" :icon="$tone === 'success' ? 'arrow-down-left' : 'arrow-up-right'">{{ $label }}</x-badge><x-money :value="$value" class="text-2xl font-extrabold block" /></section>@endforeach</div>
    <div class="grid lg:grid-cols-3 gap-6 items-start">
        <section class="panel stack lg:col-span-2"><h2>Komposisi pengeluaran</h2><p class="muted">Setiap bar menunjukkan bagian kategori dari total pengeluaran. Nilai lengkap tersedia di bawah.</p>
            @if(count($chartData))<x-report-chart :values="$chartData" :total="$totalExpense" />@endif
            @forelse($chartData as $index => $value)
            <div class="chart-row" data-chart-label="{{ $index }}" data-palette="{{ ['teal', 'violet', 'orange', 'sky', 'lime', 'indigo', 'stone', 'yellow'][$index % 8] }}"><div class="page-header"><h3 class="text-base break-words">{{ $chartLabels[$index] }}</h3><x-money :value="$value" class="font-bold" /></div><p class="muted">{{ number_format($totalExpense > 0 ? ($value / $totalExpense) * 100 : 0, 1, ',', '.') }}% dari pengeluaran periode ini.</p></div>
            @empty<x-empty-state title="Belum ada pengeluaran" text="Grafik akan terisi setelah ada pengeluaran pada periode ini." icon="chart-bar" />@endforelse
        </section>
        <div class="stack"><section class="panel stack"><h2>Estimasi tagihan bulanan</h2><x-money :value="$totalEstimatedBills" class="text-2xl font-extrabold block" /><p class="muted">Estimasi dari daftar tagihan rutin, tidak mengikuti filter periode.</p>@php($billPercentage = $totalIncome > 0 ? ($totalEstimatedBills / $totalIncome) * 100 : 0)<x-progress :value="$billPercentage" label="Estimasi tagihan terhadap pemasukan" /><p class="muted">{{ number_format($billPercentage, 1, ',', '.') }}% dari pemasukan periode ini.</p></section><section class="panel stack"><h2>Pemasukan setelah estimasi tagihan</h2><x-money :value="$disposableIncome" class="text-2xl font-extrabold block" /><p class="muted">Pemasukan periode ini dikurangi estimasi tagihan bulanan; bukan saldo kantong.</p></section></div>
    </div>
</div>
</x-app-layout>
